"""VectorStore protocol."""

from __future__ import annotations

from typing import Protocol

from ragv.models import Chunk


class VectorStore(Protocol):
    def add(self, chunks: list[Chunk], embeddings: list[list[float]]) -> None: ...
    def search(self, query_embedding: list[float], k: int) -> list[tuple[Chunk, float]]: ...
    def chunks(self) -> list[Chunk]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
